### ISSUE TITLE
Lumen UI Roadmap

### ISSUE THREAD

**Issue by philippjfr** [holoviz/lumen#214]
Meta-issue to collect important improvements to the Lumen UI before a first release:

- [ ] Add CLI command to launch `lumen gui` with options to configure UI
- [ ] Auto-generate forms for custom components
- [ ] Add UI to configure filters
- [ ] Add UI to configure transforms
- [ ] Improve UI for editing layouts
- [ ] Establish plugin system for launchers
- [ ] Establish way to build UI for custom lumen components
- [ ] Figure out permissions model for persisting/editing/adding components

**Comment by ghostiee-11** [comment]
stale
